### ISSUE TITLE
Enable TLS Rotation for Swarm Reverse Proxy

### ISSUE THREAD

**Issue by mckornfield** [Greenstand/treetracker-infrastructure#1]
Currently the swarm setup can initially have a cert stored as a secret, but we need to run a job/ service to re-issue the certbot renewal request, rotate the new cert into the swarm secrets, and restart.

**Comment by mckornfield** [comment]
So I thought about this more and wanted to document what I think should be done:

Info on running cron as a service is here: https://github.com/moby/moby/issues/23880
1) Start a cron job service, using https://github.com/crazy-max/swarm-cronjob or something like it, that runs certbot on a daily - weekly basis
2) Once certbot runs, it will update the cert on ANY of the hosts (this part is tricky, since each host is a reverse proxy)
3) Each node will have to have a cron or a running process that checks to see if the cert has been updated. This process will then load the fullchain and private key into the docker secrets
4) Restart the reverse proxy service

This is a bit convoluted I realize. This can also be done by only running the reverse proxy on a single node, which makes the swarm way less fault tolerant, but 🤷‍♂ . The way this would then work is the same as above, except certbot can be run with a normal cron, and the file listener can just be installed on the one node.

Just some of my thoughts I wanted to share. I want to go for plan one since it feels like the more correct way, but will fall back to running on one node if there's a problem.

**Comment by deepwinter** [comment]
I was reading about this a bit, and one of the ways people handle it is by running a dedicated, separate instance that just calls certbot renew daily (actually the default certbot autorenew seems to run twice a day), this node ONLY does this, it's not a normal reverse proxy node.  And then people use of the other challenge responses, since the usual single host one won't work in a load balanced scenario.   there is dns-01 https://docs.certifytheweb.com/docs/dns-validation.html, and a couple others beyond the default one certbot uses when it runs.

It's fine to have a delay between the dedicated renewal node getting the cert and the nginx servers updating to use the newest cert - both will be active for several hours, as I've been reading cert revocation is pretty slow, and that's another reason to just rotate certs all the time.  

Another interesting thing, (and sorry if I am stating something obvious) is that it's not technically necessary for each node to have the same certificate, they can all request their own and that's just ducky.  The main problem with doing this handling the challenge.    I hacked my way past this behind a load balancer by just issuing certbot requests until the round robin hit the node that was requesting the new cert... obviously not a production ready idea but hey!

**Comment by mckornfield** [comment]
Interesting... I could maybe make the CI treetracker node the cert renewer then... and I would just need to rotate the certs into a secret (that way it can be mounted in across nodes most easily). Makes sense they don't need the same cert.

**Comment by mckornfield** [comment]
I decided to just run a chron that uses a script on one node. This is done in a few commits, but here https://github.com/Greenstand/treetracker-infrastructure/commit/bf7d83434d86cdc307e8325fadc438104eaeb7bd need to test some more

**Comment by mckornfield** [comment]
Got it working and verified. Will close for now.
